#! /usr/bin/env bash

name=$1

if [ "$name" == "" ]; then
    echo "Usage: $0 ModuleName"
    exit 1
fi

day=$(date '+%e' | tr -d ' ')
read -p "Date (default: $day): " other_day

if [ "$other_day" != "" ]; then
    day=$other_day
fi

dirname="$day-$name"
mix new $dirname --app aoc --module $name
rm -f $dirname/README.md
rm -f $dirname/.formatter.exs
ln -s ../.formatter.exs $dirname/.formatter.exs

cookie=$(cat .aoc_cookies)
echo -n "Fetching input file..."
curl -s -H "cookie: $cookie" https://adventofcode.com/2020/day/$day/input -o $dirname/input.txt
echo " done."

cmd="code $dirname"
echo -n $cmd | pbcopy
echo "Next: run \`$cmd\`.  It's on the clipboard."
